pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'Building...'
        sh 'cd ../../'
        sh './gradlew -p ./microservice/service/cart build'
      }
    }
    stage('Test') { 
        steps {
          echo 'Testing...'
          }
          }
    stage('Deploy'){
        steps{
        load "/var/lib/jenkins/.envvars/var.groovy"
        echo 'Deploying...'
        echo 'Uploading artifact to s3...'
        sh "python3 s3.py ./microservice/service/cart/build/libs/cart-microservice-0.6.$BUILD_NUMBER.jar ${env.BUCKET_NAME} cart.jar"
        }
    }
    stage('Archive Artifacts') {
      steps {
        archiveArtifacts(fingerprint: true, artifacts: '**/*.jar')
      }
    }

  }
}

