def B_NAME
pipeline {
  agent any
  stages {
    stage('Pre Build') {
      steps {
         script{
        load "/var/lib/jenkins/.envvars/var.groovy"
        echo "${env.BUCKET_NAME}"
        B_NAME="${env.BUCKET_NAME}"
        }
      }
    }
    stage('Build') {
      steps {
        echo 'Building...'
        sh 'cd ../../../'
        sh './gradlew -p ./microservice/service/cart build'
      }
    }
    stage('Test') { 
        steps {
          echo 'Testing...'
          echo '$B_NAME'
          }
    }
    stage('Deploy'){
        steps{
         echo 'Deploying...'
         load "/var/lib/jenkins/.envvars/var.groovy"
         echo 'Uploading artifact to s3...'
         sh 'python3 s3.py microservice/service/cart/build/libs/cart-microservice-0.6.$BUILD_NUMBER.jar ${env.BUCKET_NAME} cart.jar'
         sh 'python3 s3.py Node_Exporter_Prometheus-1575384595496.json ${env.BUCKET_NAME} Node_Exporter_Prometheus-1575384595496.json'
        }
    }
//need to fix build num
    stage('Archive Artifacts') {
      steps {
        archiveArtifacts(fingerprint: true, artifacts: '**/*.jar')
      }
    }

  }
}

